;;; tsc-obsolete.el --- Obsolete tree-sitter APIs -*- lexical-binding: t; coding: utf-8-*-

;; Copyright (C) 2020 Tuấn-Anh Nguyễn
;; SPDX-License-Identifier: MIT

;;; Commentary:

;; This file contains obsolete `tsc' functions, kept around for temporary
;; backward compatibility. They will eventually be removed.

;;; Code:

;;; Public.
(define-obsolete-function-alias 'ts-changed-ranges 'tsc-changed-ranges "2020-10-13")
(define-obsolete-function-alias 'ts-count-children 'tsc-count-children "2020-10-13")
(define-obsolete-function-alias 'ts-count-named-children 'tsc-count-named-children "2020-10-13")
(define-obsolete-function-alias 'ts-current-field 'tsc-current-field "2020-10-13")
(define-obsolete-function-alias 'ts-current-field-id 'tsc-current-field-id "2020-10-13")
(define-obsolete-function-alias 'ts-current-node 'tsc-current-node "2020-10-13")
(define-obsolete-function-alias 'ts-cursor-p 'tsc-cursor-p "2020-10-13")
(define-obsolete-function-alias 'ts-dyn-get 'tsc-dyn-get "2020-10-13")
(define-obsolete-function-alias 'ts-dyn-get-ensure 'tsc-dyn-get-ensure "2020-10-13")
(define-obsolete-function-alias 'ts-edit-node 'tsc-edit-node "2020-10-13")
(define-obsolete-function-alias 'ts-edit-tree 'tsc-edit-tree "2020-10-13")
(define-obsolete-function-alias 'ts-get-child-by-field 'tsc-get-child-by-field "2020-10-13")
(define-obsolete-function-alias 'ts-get-child-by-field-id 'tsc-get-child-by-field-id "2020-10-13")
(define-obsolete-function-alias 'ts-get-descendant-for-byte-range 'tsc-get-descendant-for-byte-range "2020-10-13")
(define-obsolete-function-alias 'ts-get-descendant-for-point-range 'tsc-get-descendant-for-point-range "2020-10-13")
(define-obsolete-function-alias 'ts-get-descendant-for-position-range 'tsc-get-descendant-for-position-range "2020-10-13")
(define-obsolete-function-alias 'ts-get-named-descendant-for-byte-range 'tsc-get-named-descendant-for-byte-range "2020-10-13")
(define-obsolete-function-alias 'ts-get-named-descendant-for-point-range 'tsc-get-named-descendant-for-point-range "2020-10-13")
(define-obsolete-function-alias 'ts-get-named-descendant-for-position-range 'tsc-get-named-descendant-for-position-range "2020-10-13")
(define-obsolete-function-alias 'ts-get-next-named-sibling 'tsc-get-next-named-sibling "2020-10-13")
(define-obsolete-function-alias 'ts-get-next-sibling 'tsc-get-next-sibling "2020-10-13")
(define-obsolete-function-alias 'ts-get-nth-child 'tsc-get-nth-child "2020-10-13")
(define-obsolete-function-alias 'ts-get-nth-named-child 'tsc-get-nth-named-child "2020-10-13")
(define-obsolete-function-alias 'ts-get-parent 'tsc-get-parent "2020-10-13")
(define-obsolete-function-alias 'ts-get-prev-named-sibling 'tsc-get-prev-named-sibling "2020-10-13")
(define-obsolete-function-alias 'ts-get-prev-sibling 'tsc-get-prev-sibling "2020-10-13")
(define-obsolete-function-alias 'ts-goto-first-child 'tsc-goto-first-child "2020-10-13")
(define-obsolete-function-alias 'ts-goto-first-child-for-byte 'tsc-goto-first-child-for-byte "2020-10-13")
(define-obsolete-function-alias 'ts-goto-first-child-for-position 'tsc-goto-first-child-for-position "2020-10-13")
(define-obsolete-function-alias 'ts-goto-next-sibling 'tsc-goto-next-sibling "2020-10-13")
(define-obsolete-function-alias 'ts-goto-parent 'tsc-goto-parent "2020-10-13")
(define-obsolete-function-alias 'ts-lang-count-fields 'tsc-lang-count-fields "2020-10-13")
(define-obsolete-function-alias 'ts-lang-count-types 'tsc-lang-count-types "2020-10-13")
(define-obsolete-function-alias 'ts-lang-field 'tsc-lang-field "2020-10-13")
(define-obsolete-function-alias 'ts-lang-field-id 'tsc-lang-field-id "2020-10-13")
(define-obsolete-function-alias 'ts-lang-node-type 'tsc-lang-node-type "2020-10-13")
(define-obsolete-function-alias 'ts-lang-node-type-id 'tsc-lang-node-type-id "2020-10-13")
(define-obsolete-function-alias 'ts-lang-node-type-named-p 'tsc-lang-node-type-named-p "2020-10-13")
(define-obsolete-function-alias 'ts-lang-version 'tsc-lang-version "2020-10-13")
(define-obsolete-function-alias 'ts-language-p 'tsc-language-p "2020-10-13")
(define-obsolete-function-alias 'ts-make-cursor 'tsc-make-cursor "2020-10-13")
(define-obsolete-function-alias 'ts-make-parser 'tsc-make-parser "2020-10-13")
(define-obsolete-function-alias 'ts-make-query 'tsc-make-query "2020-10-13")
(define-obsolete-function-alias 'ts-make-query-cursor 'tsc-make-query-cursor "2020-10-13")
(define-obsolete-function-alias 'ts-mapc-children 'tsc-mapc-children "2020-10-13")
(define-obsolete-function-alias 'ts-node-byte-range 'tsc-node-byte-range "2020-10-13")
(define-obsolete-function-alias 'ts-node-end-byte 'tsc-node-end-byte "2020-10-13")
(define-obsolete-function-alias 'ts-node-end-point 'tsc-node-end-point "2020-10-13")
(define-obsolete-function-alias 'ts-node-end-position 'tsc-node-end-position "2020-10-13")
(define-obsolete-function-alias 'ts-node-eq 'tsc-node-eq "2020-10-13")
(define-obsolete-function-alias 'ts-node-error-p 'tsc-node-error-p "2020-10-13")
(define-obsolete-function-alias 'ts-node-extra-p 'tsc-node-extra-p "2020-10-13")
(define-obsolete-function-alias 'ts-node-has-changes-p 'tsc-node-has-changes-p "2020-10-13")
(define-obsolete-function-alias 'ts-node-has-error-p 'tsc-node-has-error-p "2020-10-13")
(define-obsolete-function-alias 'ts-node-missing-p 'tsc-node-missing-p "2020-10-13")
(define-obsolete-function-alias 'ts-node-named-p 'tsc-node-named-p "2020-10-13")
(define-obsolete-function-alias 'ts-node-p 'tsc-node-p "2020-10-13")
(define-obsolete-function-alias 'ts-node-position-range 'tsc-node-position-range "2020-10-13")
(define-obsolete-function-alias 'ts-node-range 'tsc-node-range "2020-10-13")
(define-obsolete-function-alias 'ts-node-start-byte 'tsc-node-start-byte "2020-10-13")
(define-obsolete-function-alias 'ts-node-start-point 'tsc-node-start-point "2020-10-13")
(define-obsolete-function-alias 'ts-node-start-position 'tsc-node-start-position "2020-10-13")
(define-obsolete-function-alias 'ts-node-text 'tsc-node-text "2020-10-13")
(define-obsolete-function-alias 'ts-node-to-sexp 'tsc-node-to-sexp "2020-10-13")
(define-obsolete-function-alias 'ts-node-type 'tsc-node-type "2020-10-13")
(define-obsolete-function-alias 'ts-node-type-id 'tsc-node-type-id "2020-10-13")
(define-obsolete-function-alias 'ts-parse-chunks 'tsc-parse-chunks "2020-10-13")
(define-obsolete-function-alias 'ts-parse-string 'tsc-parse-string "2020-10-13")
(define-obsolete-function-alias 'ts-parser-language 'tsc-parser-language "2020-10-13")
(define-obsolete-function-alias 'ts-parser-p 'tsc-parser-p "2020-10-13")
(define-obsolete-function-alias 'ts-point-from-position 'tsc-point-from-position "2020-10-13")
(define-obsolete-function-alias 'ts-point-p 'tsc-point-p "2020-10-13")
(define-obsolete-function-alias 'ts-point-to-position 'tsc-point-to-position "2020-10-13")
(define-obsolete-function-alias 'ts-pp-to-string 'tsc-pp-to-string "2020-10-13")
(define-obsolete-function-alias 'ts-query-capture-tags 'tsc-query-capture-tags "2020-10-13")
(define-obsolete-function-alias 'ts-query-captures 'tsc-query-captures "2020-10-13")
(define-obsolete-function-alias 'ts-query-count-patterns 'tsc-query-count-patterns "2020-10-13")
(define-obsolete-function-alias 'ts-query-cursor-p 'tsc-query-cursor-p "2020-10-13")
(define-obsolete-function-alias 'ts-query-matches 'tsc-query-matches "2020-10-13")
(define-obsolete-function-alias 'ts-query-p 'tsc-query-p "2020-10-13")
(define-obsolete-function-alias 'ts-range-p 'tsc-range-p "2020-10-13")
(define-obsolete-function-alias 'ts-reset-cursor 'tsc-reset-cursor "2020-10-13")
(define-obsolete-function-alias 'ts-root-node 'tsc-root-node "2020-10-13")
(define-obsolete-function-alias 'ts-set-included-ranges 'tsc-set-included-ranges "2020-10-13")
(define-obsolete-function-alias 'ts-set-language 'tsc-set-language "2020-10-13")
(define-obsolete-function-alias 'ts-tree-language 'tsc-tree-language "2020-10-13")
(define-obsolete-function-alias 'ts-tree-p 'tsc-tree-p "2020-10-13")
(define-obsolete-function-alias 'ts-tree-to-sexp 'tsc-tree-to-sexp "2020-10-13")

;;; Semi-public.
(define-obsolete-function-alias 'ts--lang-symbol 'tsc--lang-symbol "2020-10-13")
(define-obsolete-function-alias 'ts--buffer-input 'tsc--buffer-input "2020-10-13")
(define-obsolete-function-alias 'ts--buffer-substring-no-properties 'tsc--buffer-substring-no-properties "2020-10-13")
(define-obsolete-function-alias 'ts--clone-tree 'tsc--clone-tree "2020-10-13")
(define-obsolete-function-alias 'ts--disable-capture 'tsc--disable-capture "2020-10-13")
(define-obsolete-function-alias 'ts--dyn-version 'tsc--dyn-version "2020-10-13")
(define-obsolete-function-alias 'ts--get-child-by-field-name 'tsc--get-child-by-field-name "2020-10-13")
(define-obsolete-function-alias 'ts--invalid-node-step 'tsc--invalid-node-step "2020-10-13")
(define-obsolete-function-alias 'ts--lang-field-id-for-name 'tsc--lang-field-id-for-name "2020-10-13")
(define-obsolete-function-alias 'ts--lang-load-file 'tsc--lang-load-file "2020-10-13")
(define-obsolete-function-alias 'ts--lang-symbol 'tsc--lang-symbol "2020-10-13")
(define-obsolete-function-alias 'ts--lang-type-id-for-name 'tsc--lang-type-id-for-name "2020-10-13")
(define-obsolete-function-alias 'ts--load-language 'tsc--load-language "2020-10-13")
(define-obsolete-function-alias 'ts--make-query 'tsc--make-query "2020-10-13")
(define-obsolete-function-alias 'ts--node-from-steps 'tsc--node-from-steps "2020-10-13")
(define-obsolete-function-alias 'ts--node-steps 'tsc--node-steps "2020-10-13")
(define-obsolete-function-alias 'ts--node-text 'tsc--node-text "2020-10-13")
(define-obsolete-function-alias 'ts--point-from-position 'tsc--point-from-position "2020-10-13")
(define-obsolete-function-alias 'ts--query-capture-names 'tsc--query-capture-names "2020-10-13")
(define-obsolete-function-alias 'ts--query-cursor-captures 'tsc--query-cursor-captures "2020-10-13")
(define-obsolete-function-alias 'ts--query-cursor-captures-1 'tsc--query-cursor-captures-1 "2020-10-13")
(define-obsolete-function-alias 'ts--query-cursor-matches 'tsc--query-cursor-matches "2020-10-13")
(define-obsolete-function-alias 'ts--query-cursor-set-byte-range 'tsc--query-cursor-set-byte-range "2020-10-13")
(define-obsolete-function-alias 'ts--query-cursor-set-point-range 'tsc--query-cursor-set-point-range "2020-10-13")
(define-obsolete-function-alias 'ts--query-start-byte-for-pattern 'tsc--query-start-byte-for-pattern "2020-10-13")
(define-obsolete-function-alias 'ts--reset-parser 'tsc--reset-parser "2020-10-13")
(define-obsolete-function-alias 'ts--save-context 'tsc--save-context "2020-10-13")
(define-obsolete-function-alias 'ts--set-timeout-micros 'tsc--set-timeout-micros "2020-10-13")
(define-obsolete-function-alias 'ts--stringify-patterns 'tsc--stringify-patterns "2020-10-13")
(define-obsolete-function-alias 'ts--timeout-micros 'tsc--timeout-micros "2020-10-13")
(define-obsolete-function-alias 'ts--try-load-dyn 'tsc--try-load-dyn "2020-10-13")
(define-obsolete-function-alias 'ts--without-restriction 'tsc--without-restriction "2020-10-13")

(provide 'tsc-obsolete)
;;; tsc-obsolete.el ends here
